language: python
python:
  - 3.5.0
  - 3.5.1
  - 3.5.2
test_card:
  - 0.1.1
install:
  - pip install -r dev-requirements.txt
  - mkdir test_card
  - cd test_card
  - wget https://github.com/obmarg/test_card/releases/download/v$TEST_CARD/test_card-$TEST_CARD-ubuntu.tar.gz -O test_card.tar.gz
  - tar xzf test_card.tar.gz
  - PORT=4000 bin/test_card start
  - sleep 1
  - cat log/*
  - bin/test_card ping
  - cd ..
script: TEST_CARD_URL=localhost:4000 py.test test --timeout=5
after_script: cd test_card && bin/test_card stop
